default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  port: 5432
  username: postgres
  password: "postgres@123"

development:
  <<: *default
  database: booklend_dev

test:
  <<: *default
  database: booklend_test

production:
  <<: *default
  database: booklend_prd
